// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.29.2
// source: event/card.proto

package event

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WelcomeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Event string `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
}

func (x *WelcomeRequest) Reset() {
	*x = WelcomeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_card_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WelcomeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WelcomeRequest) ProtoMessage() {}

func (x *WelcomeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_card_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WelcomeRequest.ProtoReflect.Descriptor instead.
func (*WelcomeRequest) Descriptor() ([]byte, []int) {
	return file_event_card_proto_rawDescGZIP(), []int{0}
}

func (x *WelcomeRequest) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

type WelcomeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *WelcomeResponse) Reset() {
	*x = WelcomeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_card_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WelcomeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WelcomeResponse) ProtoMessage() {}

func (x *WelcomeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_card_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WelcomeResponse.ProtoReflect.Descriptor instead.
func (*WelcomeResponse) Descriptor() ([]byte, []int) {
	return file_event_card_proto_rawDescGZIP(), []int{1}
}

func (x *WelcomeResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type SendCardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cards  []int32 `protobuf:"varint,1,rep,packed,name=cards,proto3" json:"cards,omitempty"`
	Target int32   `protobuf:"varint,2,opt,name=target,proto3" json:"target,omitempty"`
}

func (x *SendCardRequest) Reset() {
	*x = SendCardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_card_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCardRequest) ProtoMessage() {}

func (x *SendCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_card_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCardRequest.ProtoReflect.Descriptor instead.
func (*SendCardRequest) Descriptor() ([]byte, []int) {
	return file_event_card_proto_rawDescGZIP(), []int{2}
}

func (x *SendCardRequest) GetCards() []int32 {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *SendCardRequest) GetTarget() int32 {
	if x != nil {
		return x.Target
	}
	return 0
}

type SendCardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *SendCardResponse) Reset() {
	*x = SendCardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_card_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCardResponse) ProtoMessage() {}

func (x *SendCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_card_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCardResponse.ProtoReflect.Descriptor instead.
func (*SendCardResponse) Descriptor() ([]byte, []int) {
	return file_event_card_proto_rawDescGZIP(), []int{3}
}

func (x *SendCardResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type DiscardCardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cards []int32 `protobuf:"varint,1,rep,packed,name=cards,proto3" json:"cards,omitempty"`
}

func (x *DiscardCardRequest) Reset() {
	*x = DiscardCardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_card_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiscardCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscardCardRequest) ProtoMessage() {}

func (x *DiscardCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_card_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscardCardRequest.ProtoReflect.Descriptor instead.
func (*DiscardCardRequest) Descriptor() ([]byte, []int) {
	return file_event_card_proto_rawDescGZIP(), []int{4}
}

func (x *DiscardCardRequest) GetCards() []int32 {
	if x != nil {
		return x.Cards
	}
	return nil
}

type DiscardCardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *DiscardCardResponse) Reset() {
	*x = DiscardCardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_card_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiscardCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscardCardResponse) ProtoMessage() {}

func (x *DiscardCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_card_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscardCardResponse.ProtoReflect.Descriptor instead.
func (*DiscardCardResponse) Descriptor() ([]byte, []int) {
	return file_event_card_proto_rawDescGZIP(), []int{5}
}

func (x *DiscardCardResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type EndTurnRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request string `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
}

func (x *EndTurnRequest) Reset() {
	*x = EndTurnRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_card_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndTurnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndTurnRequest) ProtoMessage() {}

func (x *EndTurnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_card_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndTurnRequest.ProtoReflect.Descriptor instead.
func (*EndTurnRequest) Descriptor() ([]byte, []int) {
	return file_event_card_proto_rawDescGZIP(), []int{6}
}

func (x *EndTurnRequest) GetRequest() string {
	if x != nil {
		return x.Request
	}
	return ""
}

type EndTurnResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *EndTurnResponse) Reset() {
	*x = EndTurnResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_card_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndTurnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndTurnResponse) ProtoMessage() {}

func (x *EndTurnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_card_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndTurnResponse.ProtoReflect.Descriptor instead.
func (*EndTurnResponse) Descriptor() ([]byte, []int) {
	return file_event_card_proto_rawDescGZIP(), []int{7}
}

func (x *EndTurnResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type NextFloorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Room int32 `protobuf:"varint,1,opt,name=room,proto3" json:"room,omitempty"`
}

func (x *NextFloorRequest) Reset() {
	*x = NextFloorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_card_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NextFloorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextFloorRequest) ProtoMessage() {}

func (x *NextFloorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_card_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextFloorRequest.ProtoReflect.Descriptor instead.
func (*NextFloorRequest) Descriptor() ([]byte, []int) {
	return file_event_card_proto_rawDescGZIP(), []int{8}
}

func (x *NextFloorRequest) GetRoom() int32 {
	if x != nil {
		return x.Room
	}
	return 0
}

type NextFloorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *NextFloorResponse) Reset() {
	*x = NextFloorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_card_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NextFloorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextFloorResponse) ProtoMessage() {}

func (x *NextFloorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_card_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextFloorResponse.ProtoReflect.Descriptor instead.
func (*NextFloorResponse) Descriptor() ([]byte, []int) {
	return file_event_card_proto_rawDescGZIP(), []int{9}
}

func (x *NextFloorResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type Bonus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type int32  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Bonus) Reset() {
	*x = Bonus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_card_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bonus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bonus) ProtoMessage() {}

func (x *Bonus) ProtoReflect() protoreflect.Message {
	mi := &file_event_card_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bonus.ProtoReflect.Descriptor instead.
func (*Bonus) Descriptor() ([]byte, []int) {
	return file_event_card_proto_rawDescGZIP(), []int{10}
}

func (x *Bonus) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Bonus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ChooseBonusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bonus []*Bonus `protobuf:"bytes,1,rep,name=bonus,proto3" json:"bonus,omitempty"`
}

func (x *ChooseBonusRequest) Reset() {
	*x = ChooseBonusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_card_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChooseBonusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChooseBonusRequest) ProtoMessage() {}

func (x *ChooseBonusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_card_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChooseBonusRequest.ProtoReflect.Descriptor instead.
func (*ChooseBonusRequest) Descriptor() ([]byte, []int) {
	return file_event_card_proto_rawDescGZIP(), []int{11}
}

func (x *ChooseBonusRequest) GetBonus() []*Bonus {
	if x != nil {
		return x.Bonus
	}
	return nil
}

type ChooseBonusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *ChooseBonusResponse) Reset() {
	*x = ChooseBonusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_card_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChooseBonusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChooseBonusResponse) ProtoMessage() {}

func (x *ChooseBonusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_card_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChooseBonusResponse.ProtoReflect.Descriptor instead.
func (*ChooseBonusResponse) Descriptor() ([]byte, []int) {
	return file_event_card_proto_rawDescGZIP(), []int{12}
}

func (x *ChooseBonusResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type UsePotionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *UsePotionRequest) Reset() {
	*x = UsePotionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_card_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UsePotionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsePotionRequest) ProtoMessage() {}

func (x *UsePotionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_card_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsePotionRequest.ProtoReflect.Descriptor instead.
func (*UsePotionRequest) Descriptor() ([]byte, []int) {
	return file_event_card_proto_rawDescGZIP(), []int{13}
}

func (x *UsePotionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UsePotionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *UsePotionResponse) Reset() {
	*x = UsePotionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_card_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UsePotionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsePotionResponse) ProtoMessage() {}

func (x *UsePotionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_card_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsePotionResponse.ProtoReflect.Descriptor instead.
func (*UsePotionResponse) Descriptor() ([]byte, []int) {
	return file_event_card_proto_rawDescGZIP(), []int{14}
}

func (x *UsePotionResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type DiscardPotionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *DiscardPotionRequest) Reset() {
	*x = DiscardPotionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_card_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiscardPotionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscardPotionRequest) ProtoMessage() {}

func (x *DiscardPotionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_card_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscardPotionRequest.ProtoReflect.Descriptor instead.
func (*DiscardPotionRequest) Descriptor() ([]byte, []int) {
	return file_event_card_proto_rawDescGZIP(), []int{15}
}

func (x *DiscardPotionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DiscardPotionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *DiscardPotionResponse) Reset() {
	*x = DiscardPotionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_card_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiscardPotionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscardPotionResponse) ProtoMessage() {}

func (x *DiscardPotionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_card_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscardPotionResponse.ProtoReflect.Descriptor instead.
func (*DiscardPotionResponse) Descriptor() ([]byte, []int) {
	return file_event_card_proto_rawDescGZIP(), []int{16}
}

func (x *DiscardPotionResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type BuyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type int32  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *BuyRequest) Reset() {
	*x = BuyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_card_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyRequest) ProtoMessage() {}

func (x *BuyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_card_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyRequest.ProtoReflect.Descriptor instead.
func (*BuyRequest) Descriptor() ([]byte, []int) {
	return file_event_card_proto_rawDescGZIP(), []int{17}
}

func (x *BuyRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *BuyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type BuyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type int32  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *BuyResponse) Reset() {
	*x = BuyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_card_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyResponse) ProtoMessage() {}

func (x *BuyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_card_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyResponse.ProtoReflect.Descriptor instead.
func (*BuyResponse) Descriptor() ([]byte, []int) {
	return file_event_card_proto_rawDescGZIP(), []int{18}
}

func (x *BuyResponse) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *BuyResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CanUseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Card int32 `protobuf:"varint,1,opt,name=card,proto3" json:"card,omitempty"`
}

func (x *CanUseRequest) Reset() {
	*x = CanUseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_card_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CanUseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanUseRequest) ProtoMessage() {}

func (x *CanUseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_card_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanUseRequest.ProtoReflect.Descriptor instead.
func (*CanUseRequest) Descriptor() ([]byte, []int) {
	return file_event_card_proto_rawDescGZIP(), []int{19}
}

func (x *CanUseRequest) GetCard() int32 {
	if x != nil {
		return x.Card
	}
	return 0
}

type CanUseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *CanUseResponse) Reset() {
	*x = CanUseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_card_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CanUseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanUseResponse) ProtoMessage() {}

func (x *CanUseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_card_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanUseResponse.ProtoReflect.Descriptor instead.
func (*CanUseResponse) Descriptor() ([]byte, []int) {
	return file_event_card_proto_rawDescGZIP(), []int{20}
}

func (x *CanUseResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

var File_event_card_proto protoreflect.FileDescriptor

var file_event_card_proto_rawDesc = []byte{
	0x0a, 0x10, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2f, 0x63, 0x61, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x26, 0x0a, 0x0e, 0x77, 0x65, 0x6c,
	0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x22, 0x29, 0x0a, 0x0f, 0x77, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x3f, 0x0a, 0x0f,
	0x73, 0x65, 0x6e, 0x64, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x63, 0x61, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x05,
	0x63, 0x61, 0x72, 0x64, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x22, 0x2a, 0x0a,
	0x10, 0x73, 0x65, 0x6e, 0x64, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x2a, 0x0a, 0x12, 0x64, 0x69, 0x73,
	0x63, 0x61, 0x72, 0x64, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x63, 0x61, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x05,
	0x63, 0x61, 0x72, 0x64, 0x73, 0x22, 0x2d, 0x0a, 0x13, 0x64, 0x69, 0x73, 0x63, 0x61, 0x72, 0x64,
	0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x22, 0x2a, 0x0a, 0x0e, 0x65, 0x6e, 0x64, 0x54, 0x75, 0x72, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x29, 0x0a, 0x0f, 0x65, 0x6e, 0x64, 0x54, 0x75, 0x72, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x26, 0x0a, 0x10, 0x6e,
	0x65, 0x78, 0x74, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x72,
	0x6f, 0x6f, 0x6d, 0x22, 0x2b, 0x0a, 0x11, 0x6e, 0x65, 0x78, 0x74, 0x46, 0x6c, 0x6f, 0x6f, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x22, 0x2f, 0x0a, 0x05, 0x42, 0x6f, 0x6e, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x38, 0x0a, 0x12, 0x63, 0x68, 0x6f, 0x6f, 0x73, 0x65, 0x42, 0x6f, 0x6e, 0x75, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x05, 0x62, 0x6f, 0x6e, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x42,
	0x6f, 0x6e, 0x75, 0x73, 0x52, 0x05, 0x62, 0x6f, 0x6e, 0x75, 0x73, 0x22, 0x2d, 0x0a, 0x13, 0x63,
	0x68, 0x6f, 0x6f, 0x73, 0x65, 0x42, 0x6f, 0x6e, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x26, 0x0a, 0x10, 0x75, 0x73,
	0x65, 0x50, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x2b, 0x0a, 0x11, 0x75, 0x73, 0x65, 0x50, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22,
	0x2a, 0x0a, 0x14, 0x64, 0x69, 0x73, 0x63, 0x61, 0x72, 0x64, 0x50, 0x6f, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2f, 0x0a, 0x15, 0x64,
	0x69, 0x73, 0x63, 0x61, 0x72, 0x64, 0x50, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x34, 0x0a, 0x0a,
	0x62, 0x75, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x35, 0x0a, 0x0b, 0x62, 0x75, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x23, 0x0a, 0x0d, 0x63, 0x61, 0x6e,
	0x55, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x61,
	0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x61, 0x72, 0x64, 0x22, 0x28,
	0x0a, 0x0e, 0x63, 0x61, 0x6e, 0x55, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0xf8, 0x04, 0x0a, 0x04, 0x63, 0x61, 0x72,
	0x64, 0x12, 0x38, 0x0a, 0x07, 0x77, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x12, 0x15, 0x2e, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x2e, 0x77, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x77, 0x65, 0x6c, 0x63,
	0x6f, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x63,
	0x61, 0x6e, 0x55, 0x73, 0x65, 0x43, 0x61, 0x72, 0x64, 0x12, 0x14, 0x2e, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x2e, 0x63, 0x61, 0x6e, 0x55, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x15, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x63, 0x61, 0x6e, 0x55, 0x73, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x43, 0x61,
	0x72, 0x64, 0x12, 0x16, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x73, 0x65, 0x6e, 0x64, 0x43,
	0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x2e, 0x73, 0x65, 0x6e, 0x64, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x0b, 0x64, 0x69, 0x73, 0x63, 0x61, 0x72, 0x64, 0x43, 0x61,
	0x72, 0x64, 0x12, 0x19, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x64, 0x69, 0x73, 0x63, 0x61,
	0x72, 0x64, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x64, 0x69, 0x73, 0x63, 0x61, 0x72, 0x64, 0x43, 0x61, 0x72,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x07, 0x65, 0x6e, 0x64,
	0x54, 0x75, 0x72, 0x6e, 0x12, 0x15, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x65, 0x6e, 0x64,
	0x54, 0x75, 0x72, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x2e, 0x65, 0x6e, 0x64, 0x54, 0x75, 0x72, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x09, 0x6e, 0x65, 0x78, 0x74, 0x46, 0x6c, 0x6f, 0x6f, 0x72,
	0x12, 0x17, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x6e, 0x65, 0x78, 0x74, 0x46, 0x6c, 0x6f,
	0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x2e, 0x6e, 0x65, 0x78, 0x74, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x0b, 0x63, 0x68, 0x6f, 0x6f, 0x73, 0x65, 0x42, 0x6f, 0x6e,
	0x75, 0x73, 0x12, 0x19, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x63, 0x68, 0x6f, 0x6f, 0x73,
	0x65, 0x42, 0x6f, 0x6e, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x63, 0x68, 0x6f, 0x6f, 0x73, 0x65, 0x42, 0x6f, 0x6e, 0x75,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x09, 0x75, 0x73, 0x65,
	0x50, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x75,
	0x73, 0x65, 0x50, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x18, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x75, 0x73, 0x65, 0x50, 0x6f, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x0d, 0x64, 0x69, 0x73,
	0x63, 0x61, 0x72, 0x64, 0x50, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x2e, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x2e, 0x64, 0x69, 0x73, 0x63, 0x61, 0x72, 0x64, 0x50, 0x6f, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e,
	0x64, 0x69, 0x73, 0x63, 0x61, 0x72, 0x64, 0x50, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x03, 0x62, 0x75, 0x79, 0x12, 0x11, 0x2e, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x2e, 0x62, 0x75, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x12, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x62, 0x75, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_event_card_proto_rawDescOnce sync.Once
	file_event_card_proto_rawDescData = file_event_card_proto_rawDesc
)

func file_event_card_proto_rawDescGZIP() []byte {
	file_event_card_proto_rawDescOnce.Do(func() {
		file_event_card_proto_rawDescData = protoimpl.X.CompressGZIP(file_event_card_proto_rawDescData)
	})
	return file_event_card_proto_rawDescData
}

var file_event_card_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_event_card_proto_goTypes = []interface{}{
	(*WelcomeRequest)(nil),        // 0: event.welcomeRequest
	(*WelcomeResponse)(nil),       // 1: event.welcomeResponse
	(*SendCardRequest)(nil),       // 2: event.sendCardRequest
	(*SendCardResponse)(nil),      // 3: event.sendCardResponse
	(*DiscardCardRequest)(nil),    // 4: event.discardCardRequest
	(*DiscardCardResponse)(nil),   // 5: event.discardCardResponse
	(*EndTurnRequest)(nil),        // 6: event.endTurnRequest
	(*EndTurnResponse)(nil),       // 7: event.endTurnResponse
	(*NextFloorRequest)(nil),      // 8: event.nextFloorRequest
	(*NextFloorResponse)(nil),     // 9: event.nextFloorResponse
	(*Bonus)(nil),                 // 10: event.Bonus
	(*ChooseBonusRequest)(nil),    // 11: event.chooseBonusRequest
	(*ChooseBonusResponse)(nil),   // 12: event.chooseBonusResponse
	(*UsePotionRequest)(nil),      // 13: event.usePotionRequest
	(*UsePotionResponse)(nil),     // 14: event.usePotionResponse
	(*DiscardPotionRequest)(nil),  // 15: event.discardPotionRequest
	(*DiscardPotionResponse)(nil), // 16: event.discardPotionResponse
	(*BuyRequest)(nil),            // 17: event.buyRequest
	(*BuyResponse)(nil),           // 18: event.buyResponse
	(*CanUseRequest)(nil),         // 19: event.canUseRequest
	(*CanUseResponse)(nil),        // 20: event.canUseResponse
}
var file_event_card_proto_depIdxs = []int32{
	10, // 0: event.chooseBonusRequest.bonus:type_name -> event.Bonus
	0,  // 1: event.card.welcome:input_type -> event.welcomeRequest
	19, // 2: event.card.canUseCard:input_type -> event.canUseRequest
	2,  // 3: event.card.sendCard:input_type -> event.sendCardRequest
	4,  // 4: event.card.discardCard:input_type -> event.discardCardRequest
	6,  // 5: event.card.endTurn:input_type -> event.endTurnRequest
	8,  // 6: event.card.nextFloor:input_type -> event.nextFloorRequest
	11, // 7: event.card.chooseBonus:input_type -> event.chooseBonusRequest
	13, // 8: event.card.usePotion:input_type -> event.usePotionRequest
	15, // 9: event.card.discardPotion:input_type -> event.discardPotionRequest
	17, // 10: event.card.buy:input_type -> event.buyRequest
	1,  // 11: event.card.welcome:output_type -> event.welcomeResponse
	20, // 12: event.card.canUseCard:output_type -> event.canUseResponse
	3,  // 13: event.card.sendCard:output_type -> event.sendCardResponse
	5,  // 14: event.card.discardCard:output_type -> event.discardCardResponse
	7,  // 15: event.card.endTurn:output_type -> event.endTurnResponse
	9,  // 16: event.card.nextFloor:output_type -> event.nextFloorResponse
	12, // 17: event.card.chooseBonus:output_type -> event.chooseBonusResponse
	14, // 18: event.card.usePotion:output_type -> event.usePotionResponse
	16, // 19: event.card.discardPotion:output_type -> event.discardPotionResponse
	18, // 20: event.card.buy:output_type -> event.buyResponse
	11, // [11:21] is the sub-list for method output_type
	1,  // [1:11] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_event_card_proto_init() }
func file_event_card_proto_init() {
	if File_event_card_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_event_card_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WelcomeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_card_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WelcomeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_card_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendCardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_card_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendCardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_card_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiscardCardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_card_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiscardCardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_card_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndTurnRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_card_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndTurnResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_card_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NextFloorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_card_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NextFloorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_card_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bonus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_card_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChooseBonusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_card_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChooseBonusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_card_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UsePotionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_card_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UsePotionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_card_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiscardPotionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_card_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiscardPotionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_card_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_card_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_card_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CanUseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_card_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CanUseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_event_card_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_event_card_proto_goTypes,
		DependencyIndexes: file_event_card_proto_depIdxs,
		MessageInfos:      file_event_card_proto_msgTypes,
	}.Build()
	File_event_card_proto = out.File
	file_event_card_proto_rawDesc = nil
	file_event_card_proto_goTypes = nil
	file_event_card_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CardClient is the client API for Card service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CardClient interface {
	Welcome(ctx context.Context, in *WelcomeRequest, opts ...grpc.CallOption) (*WelcomeResponse, error)
	CanUseCard(ctx context.Context, in *CanUseRequest, opts ...grpc.CallOption) (*CanUseResponse, error)
	SendCard(ctx context.Context, in *SendCardRequest, opts ...grpc.CallOption) (*SendCardResponse, error)
	DiscardCard(ctx context.Context, in *DiscardCardRequest, opts ...grpc.CallOption) (*DiscardCardResponse, error)
	EndTurn(ctx context.Context, in *EndTurnRequest, opts ...grpc.CallOption) (*EndTurnResponse, error)
	NextFloor(ctx context.Context, in *NextFloorRequest, opts ...grpc.CallOption) (*NextFloorResponse, error)
	ChooseBonus(ctx context.Context, in *ChooseBonusRequest, opts ...grpc.CallOption) (*ChooseBonusResponse, error)
	UsePotion(ctx context.Context, in *UsePotionRequest, opts ...grpc.CallOption) (*UsePotionResponse, error)
	DiscardPotion(ctx context.Context, in *DiscardPotionRequest, opts ...grpc.CallOption) (*DiscardPotionResponse, error)
	Buy(ctx context.Context, in *BuyRequest, opts ...grpc.CallOption) (*BuyResponse, error)
}

type cardClient struct {
	cc grpc.ClientConnInterface
}

func NewCardClient(cc grpc.ClientConnInterface) CardClient {
	return &cardClient{cc}
}

func (c *cardClient) Welcome(ctx context.Context, in *WelcomeRequest, opts ...grpc.CallOption) (*WelcomeResponse, error) {
	out := new(WelcomeResponse)
	err := c.cc.Invoke(ctx, "/event.card/welcome", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardClient) CanUseCard(ctx context.Context, in *CanUseRequest, opts ...grpc.CallOption) (*CanUseResponse, error) {
	out := new(CanUseResponse)
	err := c.cc.Invoke(ctx, "/event.card/canUseCard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardClient) SendCard(ctx context.Context, in *SendCardRequest, opts ...grpc.CallOption) (*SendCardResponse, error) {
	out := new(SendCardResponse)
	err := c.cc.Invoke(ctx, "/event.card/sendCard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardClient) DiscardCard(ctx context.Context, in *DiscardCardRequest, opts ...grpc.CallOption) (*DiscardCardResponse, error) {
	out := new(DiscardCardResponse)
	err := c.cc.Invoke(ctx, "/event.card/discardCard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardClient) EndTurn(ctx context.Context, in *EndTurnRequest, opts ...grpc.CallOption) (*EndTurnResponse, error) {
	out := new(EndTurnResponse)
	err := c.cc.Invoke(ctx, "/event.card/endTurn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardClient) NextFloor(ctx context.Context, in *NextFloorRequest, opts ...grpc.CallOption) (*NextFloorResponse, error) {
	out := new(NextFloorResponse)
	err := c.cc.Invoke(ctx, "/event.card/nextFloor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardClient) ChooseBonus(ctx context.Context, in *ChooseBonusRequest, opts ...grpc.CallOption) (*ChooseBonusResponse, error) {
	out := new(ChooseBonusResponse)
	err := c.cc.Invoke(ctx, "/event.card/chooseBonus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardClient) UsePotion(ctx context.Context, in *UsePotionRequest, opts ...grpc.CallOption) (*UsePotionResponse, error) {
	out := new(UsePotionResponse)
	err := c.cc.Invoke(ctx, "/event.card/usePotion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardClient) DiscardPotion(ctx context.Context, in *DiscardPotionRequest, opts ...grpc.CallOption) (*DiscardPotionResponse, error) {
	out := new(DiscardPotionResponse)
	err := c.cc.Invoke(ctx, "/event.card/discardPotion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardClient) Buy(ctx context.Context, in *BuyRequest, opts ...grpc.CallOption) (*BuyResponse, error) {
	out := new(BuyResponse)
	err := c.cc.Invoke(ctx, "/event.card/buy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CardServer is the server API for Card service.
type CardServer interface {
	Welcome(context.Context, *WelcomeRequest) (*WelcomeResponse, error)
	CanUseCard(context.Context, *CanUseRequest) (*CanUseResponse, error)
	SendCard(context.Context, *SendCardRequest) (*SendCardResponse, error)
	DiscardCard(context.Context, *DiscardCardRequest) (*DiscardCardResponse, error)
	EndTurn(context.Context, *EndTurnRequest) (*EndTurnResponse, error)
	NextFloor(context.Context, *NextFloorRequest) (*NextFloorResponse, error)
	ChooseBonus(context.Context, *ChooseBonusRequest) (*ChooseBonusResponse, error)
	UsePotion(context.Context, *UsePotionRequest) (*UsePotionResponse, error)
	DiscardPotion(context.Context, *DiscardPotionRequest) (*DiscardPotionResponse, error)
	Buy(context.Context, *BuyRequest) (*BuyResponse, error)
}

// UnimplementedCardServer can be embedded to have forward compatible implementations.
type UnimplementedCardServer struct {
}

func (*UnimplementedCardServer) Welcome(context.Context, *WelcomeRequest) (*WelcomeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Welcome not implemented")
}
func (*UnimplementedCardServer) CanUseCard(context.Context, *CanUseRequest) (*CanUseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CanUseCard not implemented")
}
func (*UnimplementedCardServer) SendCard(context.Context, *SendCardRequest) (*SendCardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendCard not implemented")
}
func (*UnimplementedCardServer) DiscardCard(context.Context, *DiscardCardRequest) (*DiscardCardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DiscardCard not implemented")
}
func (*UnimplementedCardServer) EndTurn(context.Context, *EndTurnRequest) (*EndTurnResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EndTurn not implemented")
}
func (*UnimplementedCardServer) NextFloor(context.Context, *NextFloorRequest) (*NextFloorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NextFloor not implemented")
}
func (*UnimplementedCardServer) ChooseBonus(context.Context, *ChooseBonusRequest) (*ChooseBonusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChooseBonus not implemented")
}
func (*UnimplementedCardServer) UsePotion(context.Context, *UsePotionRequest) (*UsePotionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UsePotion not implemented")
}
func (*UnimplementedCardServer) DiscardPotion(context.Context, *DiscardPotionRequest) (*DiscardPotionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DiscardPotion not implemented")
}
func (*UnimplementedCardServer) Buy(context.Context, *BuyRequest) (*BuyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Buy not implemented")
}

func RegisterCardServer(s *grpc.Server, srv CardServer) {
	s.RegisterService(&_Card_serviceDesc, srv)
}

func _Card_Welcome_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WelcomeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardServer).Welcome(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event.card/Welcome",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardServer).Welcome(ctx, req.(*WelcomeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Card_CanUseCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CanUseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardServer).CanUseCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event.card/CanUseCard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardServer).CanUseCard(ctx, req.(*CanUseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Card_SendCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardServer).SendCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event.card/SendCard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardServer).SendCard(ctx, req.(*SendCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Card_DiscardCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscardCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardServer).DiscardCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event.card/DiscardCard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardServer).DiscardCard(ctx, req.(*DiscardCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Card_EndTurn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndTurnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardServer).EndTurn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event.card/EndTurn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardServer).EndTurn(ctx, req.(*EndTurnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Card_NextFloor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NextFloorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardServer).NextFloor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event.card/NextFloor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardServer).NextFloor(ctx, req.(*NextFloorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Card_ChooseBonus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChooseBonusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardServer).ChooseBonus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event.card/ChooseBonus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardServer).ChooseBonus(ctx, req.(*ChooseBonusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Card_UsePotion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsePotionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardServer).UsePotion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event.card/UsePotion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardServer).UsePotion(ctx, req.(*UsePotionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Card_DiscardPotion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscardPotionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardServer).DiscardPotion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event.card/DiscardPotion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardServer).DiscardPotion(ctx, req.(*DiscardPotionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Card_Buy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardServer).Buy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event.card/Buy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardServer).Buy(ctx, req.(*BuyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Card_serviceDesc = grpc.ServiceDesc{
	ServiceName: "event.card",
	HandlerType: (*CardServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "welcome",
			Handler:    _Card_Welcome_Handler,
		},
		{
			MethodName: "canUseCard",
			Handler:    _Card_CanUseCard_Handler,
		},
		{
			MethodName: "sendCard",
			Handler:    _Card_SendCard_Handler,
		},
		{
			MethodName: "discardCard",
			Handler:    _Card_DiscardCard_Handler,
		},
		{
			MethodName: "endTurn",
			Handler:    _Card_EndTurn_Handler,
		},
		{
			MethodName: "nextFloor",
			Handler:    _Card_NextFloor_Handler,
		},
		{
			MethodName: "chooseBonus",
			Handler:    _Card_ChooseBonus_Handler,
		},
		{
			MethodName: "usePotion",
			Handler:    _Card_UsePotion_Handler,
		},
		{
			MethodName: "discardPotion",
			Handler:    _Card_DiscardPotion_Handler,
		},
		{
			MethodName: "buy",
			Handler:    _Card_Buy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "event/card.proto",
}
