// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: event/card.proto

package event

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WelcomeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         string                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WelcomeRequest) Reset() {
	*x = WelcomeRequest{}
	mi := &file_event_card_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WelcomeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WelcomeRequest) ProtoMessage() {}

func (x *WelcomeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_card_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WelcomeRequest.ProtoReflect.Descriptor instead.
func (*WelcomeRequest) Descriptor() ([]byte, []int) {
	return file_event_card_proto_rawDescGZIP(), []int{0}
}

func (x *WelcomeRequest) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

type WelcomeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WelcomeResponse) Reset() {
	*x = WelcomeResponse{}
	mi := &file_event_card_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WelcomeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WelcomeResponse) ProtoMessage() {}

func (x *WelcomeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_card_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WelcomeResponse.ProtoReflect.Descriptor instead.
func (*WelcomeResponse) Descriptor() ([]byte, []int) {
	return file_event_card_proto_rawDescGZIP(), []int{1}
}

func (x *WelcomeResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type SendCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         []int32                `protobuf:"varint,1,rep,packed,name=cards,proto3" json:"cards,omitempty"`
	Target        int32                  `protobuf:"varint,2,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCardRequest) Reset() {
	*x = SendCardRequest{}
	mi := &file_event_card_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCardRequest) ProtoMessage() {}

func (x *SendCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_card_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCardRequest.ProtoReflect.Descriptor instead.
func (*SendCardRequest) Descriptor() ([]byte, []int) {
	return file_event_card_proto_rawDescGZIP(), []int{2}
}

func (x *SendCardRequest) GetCards() []int32 {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *SendCardRequest) GetTarget() int32 {
	if x != nil {
		return x.Target
	}
	return 0
}

type SendCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCardResponse) Reset() {
	*x = SendCardResponse{}
	mi := &file_event_card_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCardResponse) ProtoMessage() {}

func (x *SendCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_card_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCardResponse.ProtoReflect.Descriptor instead.
func (*SendCardResponse) Descriptor() ([]byte, []int) {
	return file_event_card_proto_rawDescGZIP(), []int{3}
}

func (x *SendCardResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type DiscardCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         []int32                `protobuf:"varint,1,rep,packed,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscardCardRequest) Reset() {
	*x = DiscardCardRequest{}
	mi := &file_event_card_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscardCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscardCardRequest) ProtoMessage() {}

func (x *DiscardCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_card_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscardCardRequest.ProtoReflect.Descriptor instead.
func (*DiscardCardRequest) Descriptor() ([]byte, []int) {
	return file_event_card_proto_rawDescGZIP(), []int{4}
}

func (x *DiscardCardRequest) GetCards() []int32 {
	if x != nil {
		return x.Cards
	}
	return nil
}

type DiscardCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscardCardResponse) Reset() {
	*x = DiscardCardResponse{}
	mi := &file_event_card_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscardCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscardCardResponse) ProtoMessage() {}

func (x *DiscardCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_card_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscardCardResponse.ProtoReflect.Descriptor instead.
func (*DiscardCardResponse) Descriptor() ([]byte, []int) {
	return file_event_card_proto_rawDescGZIP(), []int{5}
}

func (x *DiscardCardResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type EndTurnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       string                 `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndTurnRequest) Reset() {
	*x = EndTurnRequest{}
	mi := &file_event_card_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndTurnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndTurnRequest) ProtoMessage() {}

func (x *EndTurnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_card_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndTurnRequest.ProtoReflect.Descriptor instead.
func (*EndTurnRequest) Descriptor() ([]byte, []int) {
	return file_event_card_proto_rawDescGZIP(), []int{6}
}

func (x *EndTurnRequest) GetRequest() string {
	if x != nil {
		return x.Request
	}
	return ""
}

type EndTurnResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndTurnResponse) Reset() {
	*x = EndTurnResponse{}
	mi := &file_event_card_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndTurnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndTurnResponse) ProtoMessage() {}

func (x *EndTurnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_card_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndTurnResponse.ProtoReflect.Descriptor instead.
func (*EndTurnResponse) Descriptor() ([]byte, []int) {
	return file_event_card_proto_rawDescGZIP(), []int{7}
}

func (x *EndTurnResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type NextFloorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          int32                  `protobuf:"varint,1,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NextFloorRequest) Reset() {
	*x = NextFloorRequest{}
	mi := &file_event_card_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NextFloorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextFloorRequest) ProtoMessage() {}

func (x *NextFloorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_card_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextFloorRequest.ProtoReflect.Descriptor instead.
func (*NextFloorRequest) Descriptor() ([]byte, []int) {
	return file_event_card_proto_rawDescGZIP(), []int{8}
}

func (x *NextFloorRequest) GetRoom() int32 {
	if x != nil {
		return x.Room
	}
	return 0
}

type NextFloorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NextFloorResponse) Reset() {
	*x = NextFloorResponse{}
	mi := &file_event_card_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NextFloorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextFloorResponse) ProtoMessage() {}

func (x *NextFloorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_card_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextFloorResponse.ProtoReflect.Descriptor instead.
func (*NextFloorResponse) Descriptor() ([]byte, []int) {
	return file_event_card_proto_rawDescGZIP(), []int{9}
}

func (x *NextFloorResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type Bonus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int32                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bonus) Reset() {
	*x = Bonus{}
	mi := &file_event_card_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bonus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bonus) ProtoMessage() {}

func (x *Bonus) ProtoReflect() protoreflect.Message {
	mi := &file_event_card_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bonus.ProtoReflect.Descriptor instead.
func (*Bonus) Descriptor() ([]byte, []int) {
	return file_event_card_proto_rawDescGZIP(), []int{10}
}

func (x *Bonus) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Bonus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ChooseBonusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bonus         []*Bonus               `protobuf:"bytes,1,rep,name=bonus,proto3" json:"bonus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChooseBonusRequest) Reset() {
	*x = ChooseBonusRequest{}
	mi := &file_event_card_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChooseBonusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChooseBonusRequest) ProtoMessage() {}

func (x *ChooseBonusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_card_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChooseBonusRequest.ProtoReflect.Descriptor instead.
func (*ChooseBonusRequest) Descriptor() ([]byte, []int) {
	return file_event_card_proto_rawDescGZIP(), []int{11}
}

func (x *ChooseBonusRequest) GetBonus() []*Bonus {
	if x != nil {
		return x.Bonus
	}
	return nil
}

type ChooseBonusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChooseBonusResponse) Reset() {
	*x = ChooseBonusResponse{}
	mi := &file_event_card_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChooseBonusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChooseBonusResponse) ProtoMessage() {}

func (x *ChooseBonusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_card_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChooseBonusResponse.ProtoReflect.Descriptor instead.
func (*ChooseBonusResponse) Descriptor() ([]byte, []int) {
	return file_event_card_proto_rawDescGZIP(), []int{12}
}

func (x *ChooseBonusResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type UsePotionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsePotionRequest) Reset() {
	*x = UsePotionRequest{}
	mi := &file_event_card_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsePotionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsePotionRequest) ProtoMessage() {}

func (x *UsePotionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_card_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsePotionRequest.ProtoReflect.Descriptor instead.
func (*UsePotionRequest) Descriptor() ([]byte, []int) {
	return file_event_card_proto_rawDescGZIP(), []int{13}
}

func (x *UsePotionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UsePotionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsePotionResponse) Reset() {
	*x = UsePotionResponse{}
	mi := &file_event_card_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsePotionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsePotionResponse) ProtoMessage() {}

func (x *UsePotionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_card_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsePotionResponse.ProtoReflect.Descriptor instead.
func (*UsePotionResponse) Descriptor() ([]byte, []int) {
	return file_event_card_proto_rawDescGZIP(), []int{14}
}

func (x *UsePotionResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type DiscardPotionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscardPotionRequest) Reset() {
	*x = DiscardPotionRequest{}
	mi := &file_event_card_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscardPotionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscardPotionRequest) ProtoMessage() {}

func (x *DiscardPotionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_card_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscardPotionRequest.ProtoReflect.Descriptor instead.
func (*DiscardPotionRequest) Descriptor() ([]byte, []int) {
	return file_event_card_proto_rawDescGZIP(), []int{15}
}

func (x *DiscardPotionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DiscardPotionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscardPotionResponse) Reset() {
	*x = DiscardPotionResponse{}
	mi := &file_event_card_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscardPotionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscardPotionResponse) ProtoMessage() {}

func (x *DiscardPotionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_card_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscardPotionResponse.ProtoReflect.Descriptor instead.
func (*DiscardPotionResponse) Descriptor() ([]byte, []int) {
	return file_event_card_proto_rawDescGZIP(), []int{16}
}

func (x *DiscardPotionResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type BuyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int32                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyRequest) Reset() {
	*x = BuyRequest{}
	mi := &file_event_card_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyRequest) ProtoMessage() {}

func (x *BuyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_card_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyRequest.ProtoReflect.Descriptor instead.
func (*BuyRequest) Descriptor() ([]byte, []int) {
	return file_event_card_proto_rawDescGZIP(), []int{17}
}

func (x *BuyRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *BuyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type BuyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int32                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyResponse) Reset() {
	*x = BuyResponse{}
	mi := &file_event_card_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyResponse) ProtoMessage() {}

func (x *BuyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_card_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyResponse.ProtoReflect.Descriptor instead.
func (*BuyResponse) Descriptor() ([]byte, []int) {
	return file_event_card_proto_rawDescGZIP(), []int{18}
}

func (x *BuyResponse) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *BuyResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_event_card_proto protoreflect.FileDescriptor

const file_event_card_proto_rawDesc = "" +
	"\n" +
	"\x10event/card.proto\x12\x05event\"&\n" +
	"\x0ewelcomeRequest\x12\x14\n" +
	"\x05event\x18\x01 \x01(\tR\x05event\")\n" +
	"\x0fwelcomeResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"?\n" +
	"\x0fsendCardRequest\x12\x14\n" +
	"\x05cards\x18\x01 \x03(\x05R\x05cards\x12\x16\n" +
	"\x06target\x18\x02 \x01(\x05R\x06target\"*\n" +
	"\x10sendCardResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"*\n" +
	"\x12discardCardRequest\x12\x14\n" +
	"\x05cards\x18\x01 \x03(\x05R\x05cards\"-\n" +
	"\x13discardCardResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"*\n" +
	"\x0eendTurnRequest\x12\x18\n" +
	"\arequest\x18\x01 \x01(\tR\arequest\")\n" +
	"\x0fendTurnResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"&\n" +
	"\x10nextFloorRequest\x12\x12\n" +
	"\x04room\x18\x01 \x01(\x05R\x04room\"+\n" +
	"\x11nextFloorResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"/\n" +
	"\x05Bonus\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"8\n" +
	"\x12chooseBonusRequest\x12\"\n" +
	"\x05bonus\x18\x01 \x03(\v2\f.event.BonusR\x05bonus\"-\n" +
	"\x13chooseBonusResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"&\n" +
	"\x10usePotionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"+\n" +
	"\x11usePotionResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"*\n" +
	"\x14discardPotionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"/\n" +
	"\x15discardPotionResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"4\n" +
	"\n" +
	"buyRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"5\n" +
	"\vbuyResponse\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name2\xbd\x04\n" +
	"\x04card\x128\n" +
	"\awelcome\x12\x15.event.welcomeRequest\x1a\x16.event.welcomeResponse\x12;\n" +
	"\bsendCard\x12\x16.event.sendCardRequest\x1a\x17.event.sendCardResponse\x12D\n" +
	"\vdiscardCard\x12\x19.event.discardCardRequest\x1a\x1a.event.discardCardResponse\x128\n" +
	"\aendTurn\x12\x15.event.endTurnRequest\x1a\x16.event.endTurnResponse\x12>\n" +
	"\tnextFloor\x12\x17.event.nextFloorRequest\x1a\x18.event.nextFloorResponse\x12D\n" +
	"\vchooseBonus\x12\x19.event.chooseBonusRequest\x1a\x1a.event.chooseBonusResponse\x12>\n" +
	"\tusePotion\x12\x17.event.usePotionRequest\x1a\x18.event.usePotionResponse\x12J\n" +
	"\rdiscardPotion\x12\x1b.event.discardPotionRequest\x1a\x1c.event.discardPotionResponse\x12,\n" +
	"\x03buy\x12\x11.event.buyRequest\x1a\x12.event.buyResponseB\tZ\a./eventb\x06proto3"

var (
	file_event_card_proto_rawDescOnce sync.Once
	file_event_card_proto_rawDescData []byte
)

func file_event_card_proto_rawDescGZIP() []byte {
	file_event_card_proto_rawDescOnce.Do(func() {
		file_event_card_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_card_proto_rawDesc), len(file_event_card_proto_rawDesc)))
	})
	return file_event_card_proto_rawDescData
}

var file_event_card_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_event_card_proto_goTypes = []any{
	(*WelcomeRequest)(nil),        // 0: event.welcomeRequest
	(*WelcomeResponse)(nil),       // 1: event.welcomeResponse
	(*SendCardRequest)(nil),       // 2: event.sendCardRequest
	(*SendCardResponse)(nil),      // 3: event.sendCardResponse
	(*DiscardCardRequest)(nil),    // 4: event.discardCardRequest
	(*DiscardCardResponse)(nil),   // 5: event.discardCardResponse
	(*EndTurnRequest)(nil),        // 6: event.endTurnRequest
	(*EndTurnResponse)(nil),       // 7: event.endTurnResponse
	(*NextFloorRequest)(nil),      // 8: event.nextFloorRequest
	(*NextFloorResponse)(nil),     // 9: event.nextFloorResponse
	(*Bonus)(nil),                 // 10: event.Bonus
	(*ChooseBonusRequest)(nil),    // 11: event.chooseBonusRequest
	(*ChooseBonusResponse)(nil),   // 12: event.chooseBonusResponse
	(*UsePotionRequest)(nil),      // 13: event.usePotionRequest
	(*UsePotionResponse)(nil),     // 14: event.usePotionResponse
	(*DiscardPotionRequest)(nil),  // 15: event.discardPotionRequest
	(*DiscardPotionResponse)(nil), // 16: event.discardPotionResponse
	(*BuyRequest)(nil),            // 17: event.buyRequest
	(*BuyResponse)(nil),           // 18: event.buyResponse
}
var file_event_card_proto_depIdxs = []int32{
	10, // 0: event.chooseBonusRequest.bonus:type_name -> event.Bonus
	0,  // 1: event.card.welcome:input_type -> event.welcomeRequest
	2,  // 2: event.card.sendCard:input_type -> event.sendCardRequest
	4,  // 3: event.card.discardCard:input_type -> event.discardCardRequest
	6,  // 4: event.card.endTurn:input_type -> event.endTurnRequest
	8,  // 5: event.card.nextFloor:input_type -> event.nextFloorRequest
	11, // 6: event.card.chooseBonus:input_type -> event.chooseBonusRequest
	13, // 7: event.card.usePotion:input_type -> event.usePotionRequest
	15, // 8: event.card.discardPotion:input_type -> event.discardPotionRequest
	17, // 9: event.card.buy:input_type -> event.buyRequest
	1,  // 10: event.card.welcome:output_type -> event.welcomeResponse
	3,  // 11: event.card.sendCard:output_type -> event.sendCardResponse
	5,  // 12: event.card.discardCard:output_type -> event.discardCardResponse
	7,  // 13: event.card.endTurn:output_type -> event.endTurnResponse
	9,  // 14: event.card.nextFloor:output_type -> event.nextFloorResponse
	12, // 15: event.card.chooseBonus:output_type -> event.chooseBonusResponse
	14, // 16: event.card.usePotion:output_type -> event.usePotionResponse
	16, // 17: event.card.discardPotion:output_type -> event.discardPotionResponse
	18, // 18: event.card.buy:output_type -> event.buyResponse
	10, // [10:19] is the sub-list for method output_type
	1,  // [1:10] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_event_card_proto_init() }
func file_event_card_proto_init() {
	if File_event_card_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_card_proto_rawDesc), len(file_event_card_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_event_card_proto_goTypes,
		DependencyIndexes: file_event_card_proto_depIdxs,
		MessageInfos:      file_event_card_proto_msgTypes,
	}.Build()
	File_event_card_proto = out.File
	file_event_card_proto_goTypes = nil
	file_event_card_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CardClient is the client API for Card service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CardClient interface {
	Welcome(ctx context.Context, in *WelcomeRequest, opts ...grpc.CallOption) (*WelcomeResponse, error)
	SendCard(ctx context.Context, in *SendCardRequest, opts ...grpc.CallOption) (*SendCardResponse, error)
	DiscardCard(ctx context.Context, in *DiscardCardRequest, opts ...grpc.CallOption) (*DiscardCardResponse, error)
	EndTurn(ctx context.Context, in *EndTurnRequest, opts ...grpc.CallOption) (*EndTurnResponse, error)
	NextFloor(ctx context.Context, in *NextFloorRequest, opts ...grpc.CallOption) (*NextFloorResponse, error)
	ChooseBonus(ctx context.Context, in *ChooseBonusRequest, opts ...grpc.CallOption) (*ChooseBonusResponse, error)
	UsePotion(ctx context.Context, in *UsePotionRequest, opts ...grpc.CallOption) (*UsePotionResponse, error)
	DiscardPotion(ctx context.Context, in *DiscardPotionRequest, opts ...grpc.CallOption) (*DiscardPotionResponse, error)
	Buy(ctx context.Context, in *BuyRequest, opts ...grpc.CallOption) (*BuyResponse, error)
}

type cardClient struct {
	cc grpc.ClientConnInterface
}

func NewCardClient(cc grpc.ClientConnInterface) CardClient {
	return &cardClient{cc}
}

func (c *cardClient) Welcome(ctx context.Context, in *WelcomeRequest, opts ...grpc.CallOption) (*WelcomeResponse, error) {
	out := new(WelcomeResponse)
	err := c.cc.Invoke(ctx, "/event.card/welcome", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardClient) SendCard(ctx context.Context, in *SendCardRequest, opts ...grpc.CallOption) (*SendCardResponse, error) {
	out := new(SendCardResponse)
	err := c.cc.Invoke(ctx, "/event.card/sendCard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardClient) DiscardCard(ctx context.Context, in *DiscardCardRequest, opts ...grpc.CallOption) (*DiscardCardResponse, error) {
	out := new(DiscardCardResponse)
	err := c.cc.Invoke(ctx, "/event.card/discardCard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardClient) EndTurn(ctx context.Context, in *EndTurnRequest, opts ...grpc.CallOption) (*EndTurnResponse, error) {
	out := new(EndTurnResponse)
	err := c.cc.Invoke(ctx, "/event.card/endTurn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardClient) NextFloor(ctx context.Context, in *NextFloorRequest, opts ...grpc.CallOption) (*NextFloorResponse, error) {
	out := new(NextFloorResponse)
	err := c.cc.Invoke(ctx, "/event.card/nextFloor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardClient) ChooseBonus(ctx context.Context, in *ChooseBonusRequest, opts ...grpc.CallOption) (*ChooseBonusResponse, error) {
	out := new(ChooseBonusResponse)
	err := c.cc.Invoke(ctx, "/event.card/chooseBonus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardClient) UsePotion(ctx context.Context, in *UsePotionRequest, opts ...grpc.CallOption) (*UsePotionResponse, error) {
	out := new(UsePotionResponse)
	err := c.cc.Invoke(ctx, "/event.card/usePotion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardClient) DiscardPotion(ctx context.Context, in *DiscardPotionRequest, opts ...grpc.CallOption) (*DiscardPotionResponse, error) {
	out := new(DiscardPotionResponse)
	err := c.cc.Invoke(ctx, "/event.card/discardPotion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardClient) Buy(ctx context.Context, in *BuyRequest, opts ...grpc.CallOption) (*BuyResponse, error) {
	out := new(BuyResponse)
	err := c.cc.Invoke(ctx, "/event.card/buy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CardServer is the server API for Card service.
type CardServer interface {
	Welcome(context.Context, *WelcomeRequest) (*WelcomeResponse, error)
	SendCard(context.Context, *SendCardRequest) (*SendCardResponse, error)
	DiscardCard(context.Context, *DiscardCardRequest) (*DiscardCardResponse, error)
	EndTurn(context.Context, *EndTurnRequest) (*EndTurnResponse, error)
	NextFloor(context.Context, *NextFloorRequest) (*NextFloorResponse, error)
	ChooseBonus(context.Context, *ChooseBonusRequest) (*ChooseBonusResponse, error)
	UsePotion(context.Context, *UsePotionRequest) (*UsePotionResponse, error)
	DiscardPotion(context.Context, *DiscardPotionRequest) (*DiscardPotionResponse, error)
	Buy(context.Context, *BuyRequest) (*BuyResponse, error)
}

// UnimplementedCardServer can be embedded to have forward compatible implementations.
type UnimplementedCardServer struct {
}

func (*UnimplementedCardServer) Welcome(context.Context, *WelcomeRequest) (*WelcomeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Welcome not implemented")
}
func (*UnimplementedCardServer) SendCard(context.Context, *SendCardRequest) (*SendCardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendCard not implemented")
}
func (*UnimplementedCardServer) DiscardCard(context.Context, *DiscardCardRequest) (*DiscardCardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DiscardCard not implemented")
}
func (*UnimplementedCardServer) EndTurn(context.Context, *EndTurnRequest) (*EndTurnResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EndTurn not implemented")
}
func (*UnimplementedCardServer) NextFloor(context.Context, *NextFloorRequest) (*NextFloorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NextFloor not implemented")
}
func (*UnimplementedCardServer) ChooseBonus(context.Context, *ChooseBonusRequest) (*ChooseBonusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChooseBonus not implemented")
}
func (*UnimplementedCardServer) UsePotion(context.Context, *UsePotionRequest) (*UsePotionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UsePotion not implemented")
}
func (*UnimplementedCardServer) DiscardPotion(context.Context, *DiscardPotionRequest) (*DiscardPotionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DiscardPotion not implemented")
}
func (*UnimplementedCardServer) Buy(context.Context, *BuyRequest) (*BuyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Buy not implemented")
}

func RegisterCardServer(s *grpc.Server, srv CardServer) {
	s.RegisterService(&_Card_serviceDesc, srv)
}

func _Card_Welcome_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WelcomeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardServer).Welcome(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event.card/Welcome",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardServer).Welcome(ctx, req.(*WelcomeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Card_SendCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardServer).SendCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event.card/SendCard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardServer).SendCard(ctx, req.(*SendCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Card_DiscardCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscardCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardServer).DiscardCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event.card/DiscardCard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardServer).DiscardCard(ctx, req.(*DiscardCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Card_EndTurn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndTurnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardServer).EndTurn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event.card/EndTurn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardServer).EndTurn(ctx, req.(*EndTurnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Card_NextFloor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NextFloorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardServer).NextFloor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event.card/NextFloor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardServer).NextFloor(ctx, req.(*NextFloorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Card_ChooseBonus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChooseBonusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardServer).ChooseBonus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event.card/ChooseBonus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardServer).ChooseBonus(ctx, req.(*ChooseBonusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Card_UsePotion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsePotionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardServer).UsePotion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event.card/UsePotion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardServer).UsePotion(ctx, req.(*UsePotionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Card_DiscardPotion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscardPotionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardServer).DiscardPotion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event.card/DiscardPotion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardServer).DiscardPotion(ctx, req.(*DiscardPotionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Card_Buy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardServer).Buy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event.card/Buy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardServer).Buy(ctx, req.(*BuyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Card_serviceDesc = grpc.ServiceDesc{
	ServiceName: "event.card",
	HandlerType: (*CardServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "welcome",
			Handler:    _Card_Welcome_Handler,
		},
		{
			MethodName: "sendCard",
			Handler:    _Card_SendCard_Handler,
		},
		{
			MethodName: "discardCard",
			Handler:    _Card_DiscardCard_Handler,
		},
		{
			MethodName: "endTurn",
			Handler:    _Card_EndTurn_Handler,
		},
		{
			MethodName: "nextFloor",
			Handler:    _Card_NextFloor_Handler,
		},
		{
			MethodName: "chooseBonus",
			Handler:    _Card_ChooseBonus_Handler,
		},
		{
			MethodName: "usePotion",
			Handler:    _Card_UsePotion_Handler,
		},
		{
			MethodName: "discardPotion",
			Handler:    _Card_DiscardPotion_Handler,
		},
		{
			MethodName: "buy",
			Handler:    _Card_Buy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "event/card.proto",
}
